version: "3.3"
services:
  db:
    build: .docker/mariadb-strict
    container_name: mariadb-strict
    ports:
      - "3306:3306"
    volumes:
      - .docker/mariadb-strict/log:/var/log/mysql
      - .docker/mariadb-strict/data:/var/lib/mysql
      - .docker/mariadb-strict/dump:/docker-entrypoint-initdb.d
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_USER=myuser
      #- MYSQL_PASSWORD=secret
      #- MYSQL_DATABASE=test
    healthcheck:
      test: "cat /proc/net/tcp /proc/net/tcp6 | grep ':0CEA'"
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db:db
    depends_on:
      - db
    environment:
      #- PMA_ARBITRARY=1
      #- MYSQL_USER=root
      #- MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      #- PMA_HOST=
    #restart: always
    ports:
      - "8181:80"
    volumes:
      - /.docker/phpmyadmin/sessions
      #- .docker/phpmyadmin
